---
kind: pipeline
type: docker
name: push-latest-build
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: lblod/harvest-check-url-collection-service
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - master
---
kind: pipeline
type: docker
name: release
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: lblod/harvest-check-url-collection-service
    dry_run: true
    purge: true
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: lblod/harvest-check-url-collection-service
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  event:
    - tag
---
kind: secret
name: docker_username
data: +2MV4q0612aWOPS+H11/3qOQHPwGL9tw2H7tGzXBVj6Dx2laQ5HP+w==
---
kind: secret
name: docker_password
data: 76eHZt/BLXUAIGM/hcanEdkNmctlcOEf0GlZMM/aP2abcmDIHQ+hXxfgIvYuzeAKVZSAWwrAbhXzFV89Slt9eQ==
---
kind: signature
hmac: 785bcadc3c5fb6d8f937c02e5f0ff3505dcfa2e4245c6979b405dca6cc6fbc33

...
